### ISSUE TITLE
rf_moritz compile failed

### ISSUE THREAD

**Issue by kroon040** [Man-fred/culfw.esp8266#3]
Hi Manfred

I see that moritz you have enabled.

It fails when I compile

Multiple libraries were found for "WiFiUdp.h"
/home/richard/Arduino/libraries/rf_moritz/rf_moritz.c:5:27: fatal error: avr/interrupt.h: No such file or directory
 Used: /home/richard/.arduino15/packages/esp8266/hardware/esp8266/2.6.3/libraries/ESP8266WiFi
 #include <avr/interrupt.h>
 Not used: /home/richard/Downloads/arduino-1.8.12/libraries/WiFi

regards Richard

**Comment by kroon040** [comment]
Manfred

I compiled the new version. Setting the network was a little difficult , dhcp didn't work, so static went ok.

I have now  4 thermostat basics 1 wallthermostat and 1 fakewallthermostat, and looks like it works

Good job. I will check tomorrow late if everything is stable

**Comment by Man-fred** [comment]
Hi Richard,
great that it works for you, my MAX!-devices seems also running, so I can rollout it in all rooms.
Regards, Manfred

**Comment by kroon040** [comment]
Manfred,

It looks stable. Only the the hostname (devicename) is not working. In the console commad Rid I get esp-cul, but on the network it shows still ESP-F44XXXX. Also reboot and/erased reflashed but not working.

regards Richard

**Comment by Man-fred** [comment]
Hi,
the problem with the hostname is a problem in dns/dhcp. Perhaps it helps to delete the name in the dns-server and then restart the esp. Then it should show the new and correct name.

**Comment by kroon040** [comment]
Hi,

Removed everything from dns/dhcp entries, erased the the esp, and reprogrammed. Tried both esps, and both gives ESP-F****

**Comment by Man-fred** [comment]
Hi,
I will test it. I have two more esp and will upload the sketch. Maybe then I can see the problem myself.

**Comment by Man-fred** [comment]
Good news: I found the error in setting the hostname. But i changed something more and must test if the changes are stable.

**Comment by kroon040** [comment]
Good to hear. Let me know when I can test it.

My 4 thermostat basic and 1 wandthermostat works fine at the moment.

**Comment by Man-fred** [comment]
Hi Richard,
I pushed the changes in testing the hostname to master. Nothing else is changed, so the stability shouldn't be affected. 
Regards, Manfred

**Comment by kroon040** [comment]
Manfred,

Now it works. the hostname comes correct in the wifi router

thnx , I close this issue. Thnx for all the support.
